In [1]:
import wandb

In [2]:
wandb.login(key = "63976e50d132e095c08d515af14997b636753e96")

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: C:\Users\tipto\.netrc
wandb: Currently logged in as: tiptoghosh (tiptoghosh-american-international-university-bangladesh) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


True

In [3]:
import pandas as pd 
import numpy as np 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
# Load the dataset
iris = load_iris()
X = iris.data
y = iris.target

In [5]:
df = pd.DataFrame(data=X, columns=iris.feature_names)
df['species'] = iris.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

Training set size: 120 samples
Testing set size: 30 samples


In [7]:
# Create a KNN model instance
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [8]:
y_pred = knn.predict(X_test)

In [9]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [10]:
# Generate and print a classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [11]:

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [12]:
wandb.init(project = "usvisa-prediction" , name = "first-run")

In [13]:
wandb.log({
    "accuracy" : accuracy_score
})

In [15]:
import joblib
joblib.dump(knn , "test_model.pkl")

['test_model.pkl']

In [ ]:
artifact = wandb.Artifact("trained-model", type="model")
artifact.add_file("model.pkl")
wandb.log_artifact(artifact)

In [16]:
artifact = wandb.Artifact(name="trained-knn-model", type="model")
artifact.add_file("test_model.pkl")

ArtifactManifestEntry(path='test_model.pkl', digest='fc7z4HdSa+jGZcmK3AzZHA==', size=11334, local_path='C:\\Users\\tipto\\AppData\\Local\\wandb\\wandb\\artifacts\\staging\\tmpkfv_9h1v', skip_cache=False)

In [17]:
wandb.log_artifact(artifact)

<Artifact trained-knn-model>

In [18]:
wandb.finish()

In [20]:
wandb.init()

In [23]:
wandb.init(project="usvisa-prediction", name="fetch-model", reinit=True)

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.


In [24]:
# fetch the artifact

In [25]:
artifact = wandb.use_artifact(
    "tiptoghosh-american-international-university-bangladesh/usvisa-prediction/trained-knn-model:latest",
    type="model"
)

In [26]:
artifact_dir = artifact.download()
artifact_dir

wandb:   1 of 1 files downloaded.  


'e:\\end-to-end-machine-learning-project\\End-To-End-MLOps-US-Visa-Prediction\\notebooks\\artifacts\\trained-knn-model-v0'

In [27]:
import os
model_path = os.path.join(artifact_dir, "test_model.pkl")

In [28]:
model = joblib.load(model_path)

In [29]:
y_pred2 = model.predict(X_test)
y_pred2.shape

(30,)

In [30]:
accuracy_score(y_test , y_pred2)

1.0

In [31]:
# delete the artifact[cause it was  a demo]
artifact.delete(delete_aliases = True)

print(f"{artifact.name} deleted")

wandb: WARNING Deleting a link artifact will only unlink the artifact from the source artifact and not delete the source artifact and the data of the source artifact.


CommError: HTTP 400: artifact collection 718881063 is not a portfolio

In [32]:
artifact = wandb.use_artifact(
    "tiptoghosh-american-international-university-bangladesh/usvisa-prediction/trained-knn-model:latest",
    type="model"
)

CommError: artifact membership 'trained-knn-model:latest' not found in 'tiptoghosh-american-international-university-bangladesh/usvisa-prediction'